// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import ImaskController from "./imask_controller"
application.register("imask", ImaskController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SwitchController from "./switch_controller"
application.register("switch", SwitchController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
